name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    # container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
          
          echo "## MODEL METRICS" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data Viz" --md > report.md
          cml_publish feature_importance.png --md >> report.md
          cml_publish residuals.png --md >> report.md
          
          cml_send_comment report.md
        
